language: python
addons:
  apt:
    packages:
    - g++
    - python-dev
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
python:
  - "2.6"
  - "2.7"
sudo: false
install:
  - "source ./install_dependencies.sh"
script: "python setup.py test"
